version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
